# Problem 2: Even Fibonacci Numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#    1, 2, 3, 5, 8, 13, 21, 34, 55, 89
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# So, sum of first 10 EVEN terms will be:
#    2 + 8 + 34 = 44


defmodule EvenFibonacciNumbers do
  @limit 4_000_000

  # METHOD 1) generates both odd and even (tail-recursion)
  def even_fib_sum_recurse1(sum, a, _) when a > @limit, do: sum   # exceed must allow 4_000_000 itself
  def even_fib_sum_recurse1(sum, a, b) when rem(a, 2) == 0, do: even_fib_sum_recurse1(sum + a, b, a + b)
  def even_fib_sum_recurse1(sum, a, b), do: even_fib_sum_recurse1(sum, b, a + b)
  def sum_of_even_fib1(), do: even_fib_sum_recurse1(0, 1, 2)

  # METHOD 2) generates even only (tail-recursion, 2nd best method)
  def even_fib_sum_recurse2(sum, a, _) when a > @limit, do: sum
  def even_fib_sum_recurse2(sum, a, b), do: even_fib_sum_recurse2(sum + a, b, a + b * 4)
  def sum_of_even_fib2(), do: even_fib_sum_recurse2(0, 2, 8)

  # METHOD 3) generates even and odd (stream)
  def sum_of_even_fib3() do
    Stream.unfold({1, 2}, fn {a, b} -> 
      if a > @limit, do: nil, else: {a, {b, a + b}}
    end)
    |> Stream.filter(&rem(&1, 2) == 0)
    |> Enum.sum()
  end

  # METHOD 4) generates even only (stream, most idiomatic + concise 🏆)
  def sum_of_even_fib4() do
    Stream.unfold({2, 8}, fn {a, b} -> 
      if a > @limit, do: nil, else: {a, {b, a + b * 4}}
    end)
    |> Enum.sum()
  end

end

EvenFibonacciNumbers.sum_of_even_fib1() |> IO.puts
EvenFibonacciNumbers.sum_of_even_fib2() |> IO.puts
EvenFibonacciNumbers.sum_of_even_fib3() |> IO.puts
EvenFibonacciNumbers.sum_of_even_fib4() |> IO.puts
IO.puts("Expected: 4613732")
